version: '1.0'

services:
  python:
    image: python:3.13.1
    container_name: python-container
    working_dir: /workspace
    volumes:
      - ../../:/workspace
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
    command: sleep infinity

  db:
    image: postgres:17.2-alpine
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sampledb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
